// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqaLYmBMkQN9-khqH1lS6HntPNIm7wO0Y',
    appId: '1:275627294897:web:6c6d9d068a2995c7752290',
    messagingSenderId: '275627294897',
    projectId: 'swapnasutr',
    authDomain: 'swapnasutr.firebaseapp.com',
    storageBucket: 'swapnasutr.firebasestorage.app',
    measurementId: 'G-N8BY66RLY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9QdZTr45FzXIRPJpR3FSj2GfShLcb2SU',
    appId: '1:275627294897:android:2e3e1f566a2f7a1b752290',
    messagingSenderId: '275627294897',
    projectId: 'swapnasutr',
    storageBucket: 'swapnasutr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPcdUfY5ux06IpYshb40krHXW_GtXD6Lg',
    appId: '1:275627294897:ios:3d4a11459f602876752290',
    messagingSenderId: '275627294897',
    projectId: 'swapnasutr',
    storageBucket: 'swapnasutr.firebasestorage.app',
    iosBundleId: 'com.dreamverse.dreamVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPcdUfY5ux06IpYshb40krHXW_GtXD6Lg',
    appId: '1:275627294897:ios:3d4a11459f602876752290',
    messagingSenderId: '275627294897',
    projectId: 'swapnasutr',
    storageBucket: 'swapnasutr.firebasestorage.app',
    iosBundleId: 'com.dreamverse.dreamVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqaLYmBMkQN9-khqH1lS6HntPNIm7wO0Y',
    appId: '1:275627294897:web:cfff044014706a6d752290',
    messagingSenderId: '275627294897',
    projectId: 'swapnasutr',
    authDomain: 'swapnasutr.firebaseapp.com',
    storageBucket: 'swapnasutr.firebasestorage.app',
    measurementId: 'G-9EPK6QP5R6',
  );
}
